Update failover.yml

diff --git a/.github/workflows/failover.yml b/.github/workflows/failover.yml
--- a/.github/workflows/failover.yml
+++ b/.github/workflows/failover.yml
@@ -2,20 +2,20 @@ name: Failover Unit Tests
 
 on:
   workflow_dispatch:
-  push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - '*'
-    paths-ignore:
-      - '**/*.md'
-      - '**/*.jpg'
-      - '**/README.txt'
-      - '**/LICENSE.txt'
-      - 'docs/**'
-      - 'ISSUE_TEMPLATE/**'
-      - '**/remove-old-artifacts.yml'
+  # push:
+  #   branches:
+  #     - main
+  # pull_request:
+  #   branches:
+  #     - '*'
+  #   paths-ignore:
+  #     - '**/*.md'
+  #     - '**/*.jpg'
+  #     - '**/README.txt'
+  #     - '**/LICENSE.txt'
+  #     - 'docs/**'
+  #     - 'ISSUE_TEMPLATE/**'
+  #     - '**/remove-old-artifacts.yml'
 
 permissions:
   id-token: write
@@ -130,24 +130,24 @@ jobs:
           if ($is_leaking) {echo $is_leaking; exit 1;}
 
       # Upload artifacts
-      - name: Upload build artifacts - Binaries
-        if: always()
-        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
-        with:
-          name: windows-failover-sln
-          path: ${{ github.workspace }}/build/MySQL_Connector_ODBC.sln
-      - name: Upload build artifacts - Binaries
-        if: always()
-        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
-        with:
-          name: windows-failover-binaries
-          path: ${{ github.workspace }}/build/bin/
-      - name: Upload build artifacts - Libraries
-        if: always()
-        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
-        with:
-          name: windows-failover-libraries
-          path: ${{ github.workspace }}/build/lib/
+      # - name: Upload build artifacts - Binaries
+      #   if: always()
+      #   uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
+      #   with:
+      #     name: windows-failover-sln
+      #     path: ${{ github.workspace }}/build/MySQL_Connector_ODBC.sln
+      # - name: Upload build artifacts - Binaries
+      #   if: always()
+      #   uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
+      #   with:
+      #     name: windows-failover-binaries
+      #     path: ${{ github.workspace }}/build/bin/
+      # - name: Upload build artifacts - Libraries
+      #   if: always()
+      #   uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
+      #   with:
+      #     name: windows-failover-libraries
+      #     path: ${{ github.workspace }}/build/lib/
       - name: Upload failover test artifacts
         if: always()
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
@@ -355,36 +355,36 @@ jobs:
         shell: bash
         run: ctest --output-on-failure
 
-      - name: Check memory leaks
-        if: always()
-        working-directory: ${{ github.workspace }}/build/unit_testing/bin
-        run:  |
-          leaks -atExit -- ./unit_testing > ../leaks_unit_testing.txt
-          export is_leaking=$?
-          if (( $is_leaking != 0 )); then echo $is_leaking; exit 1; else echo "no memory leaks"; fi;
+      # - name: Check memory leaks
+      #   if: always()
+      #   working-directory: ${{ github.workspace }}/build/unit_testing/bin
+      #   run:  |
+      #     leaks -atExit -- ./unit_testing > ../leaks_unit_testing.txt
+      #     export is_leaking=$?
+      #     if (( $is_leaking != 0 )); then echo $is_leaking; exit 1; else echo "no memory leaks"; fi;
 
       # Upload artifacts
-      - name: Upload build artifacts - Binaries
-        if: always()
-        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
-        with:
-          name: macos-binaries
-          path: ${{ github.workspace }}/build/bin/
-      - name: Upload build artifacts - Libraries
-        if: always()
-        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
-        with:
-          name: macos-libraries
-          path: ${{ github.workspace }}/build/lib/
+      # - name: Upload build artifacts - Binaries
+      #   if: always()
+      #   uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
+      #   with:
+      #     name: macos-binaries
+      #     path: ${{ github.workspace }}/build/bin/
+      # - name: Upload build artifacts - Libraries
+      #   if: always()
+      #   uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
+      #   with:
+      #     name: macos-libraries
+      #     path: ${{ github.workspace }}/build/lib/
       - name: Upload test artifacts
         if: always()
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
         with:
           name: macos-failover-results
           path: ${{ github.workspace }}/build/unit_testing/Testing/Temporary/LastTest.log
-      - name: Upload memory leaks check
-        if: always()
-        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
-        with:
-          name: macos-memory-leaks-results
-          path: ${{ github.workspace }}/build/unit_testing/leaks_unit_testing.txt
+      # - name: Upload memory leaks check
+      #   if: always()
+      #   uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
+      #   with:
+      #     name: macos-memory-leaks-results
+      #     path: ${{ github.workspace }}/build/unit_testing/leaks_unit_testing.txt
